### ISSUE TITLE
After installing numpy and pandas in Python 3.9.*, `ERROR: No matching distribution found for tensorflow==1.15`

### ISSUE THREAD

**Issue by sgbaird** [aspuru-guzik-group/olympus#24]
```python
(base) PS C:\Users\sterg\Documents\GitHub\sparks-baird\self-driving-lab-demo> conda create -n olymp python==3.9.*
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\sterg\Miniconda3\envs\olymp

  added / updated specs:
    - python=3.9


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2022.10.11-haa95532_0 None
  certifi            pkgs/main/win-64::certifi-2022.9.24-py39haa95532_0 None
  openssl            pkgs/main/win-64::openssl-1.1.1s-h2bbff1b_0 None
  pip                pkgs/main/win-64::pip-22.2.2-py39haa95532_0 None
  python             pkgs/main/win-64::python-3.9.13-h6244533_2 None
  setuptools         pkgs/main/win-64::setuptools-65.5.0-py39haa95532_0 None
  sqlite             pkgs/main/win-64::sqlite-3.39.3-h2bbff1b_0 None
  tzdata             pkgs/main/noarch::tzdata-2022f-h04d1e81_0 None
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1 None
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2 None
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0 None
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py39haa95532_2 None


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate olymp
#
# To deactivate an active environment, use   
#
#     $ conda deactivate

Retrieving notices: ...working... done       
(base) PS C:\Users\sterg\Documents\GitHub\sparks-baird\self-driving-lab-demo> conda activate olymp
(olymp) PS C:\Users\sterg\Documents\GitHub\sparks-baird\self-driving-lab-demo> pip install olymp[all]
Collecting olymp[all]
  Using cached olymp-0.0.1b0-py3-none-any.whl (4.8 MB)
Collecting numpy
  Downloading numpy-1.23.4-cp39-cp39-win_amd64.whl (14.7 MB)
     ━━━━━━━━━ 14.7/14.7 5.6 MB/s eta 0:00:00
               MB
Collecting pandas
  Downloading pandas-1.5.1-cp39-cp39-win_amd64.whl (10.9 MB)
     ━━━━━━━━━ 10.9/10.9 6.2 MB/s eta 0:00:00
               MB
Collecting deap
  Downloading deap-1.3.3-cp39-cp39-win_amd64.whl (114 kB)
     ━━━━━━━━━ 114.3/11… 6.5 MB/s eta 0:00:00
               kB
Collecting seaborn
  Using cached seaborn-0.12.1-py3-none-any.whl (288 kB)
Collecting tensorflow-probability==0.8
  Downloading tensorflow_probability-0.8.0-py2.py3-none-any.whl (2.5 MB)
     ━━━━━━━━━ 2.5/2.5   5.4 MB/s eta 0:00:00
               MB
Collecting pyswarms
  Downloading pyswarms-1.3.0-py2.py3-none-any.whl (104 kB)
     ━━━━━━━━━━━━ 104.1/104.1   ? eta 0:00:00
                  kB
Collecting sqlalchemy
  Downloading SQLAlchemy-1.4.44-cp39-cp39-win_amd64.whl (1.6 MB)
     ━━━━━━━━━ 1.6/1.6   5.6 MB/s eta 0:00:00
               MB
Collecting hyperopt
  Downloading hyperopt-0.2.7-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━ 1.6/1.6   5.9 MB/s eta 0:00:00
               MB
Collecting phoenics
  Downloading phoenics-0.2.0.tar.gz (177 kB)
     ━━━━━━━━━ 177.7/17… 5.4 MB/s eta 0:00:00
               kB
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error        

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):     
        File "<string>", line 2, in <module> 
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\sterg\AppData\Local\Temp\pip-install-j1gm7ni6\phoenics_cd91286c19644e1382e889fb4f980ef6\setup.py", line 5, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.    
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details
```

```python
(olymp) PS C:\Users\sterg\Documents\GitHub\sparks-baird\self-driving-lab-demo> pip install numpy pandas
Collecting numpy
  Using cached numpy-1.23.4-cp39-cp39-win_amd64.whl (14.7 MB)
Collecting pandas
  Using cached pandas-1.5.1-cp39-cp39-win_amd64.whl (10.9 MB)
Collecting pytz>=2020.1
  Downloading pytz-2022.6-py2.py3-none-any.whl (498 kB)
     ━━━━━━━━━ 498.1/49… 2.6 MB/s eta 0:00:00
               kB
Collecting python-dateutil>=2.8.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, six, numpy, python-dateutil, pandas
Successfully installed numpy-1.23.4 pandas-1.5.1 python-dateutil-2.8.2 pytz-2022.6 six-1.16.0
(olymp) PS C:\Users\sterg\Documents\GitHub\sparks-baird\self-driving-lab-demo> pip install olymp[all]  
Collecting olymp[all]
  Using cached olymp-0.0.1b0-py3-none-any.whl (4.8 MB)
Requirement already satisfied: pandas in c:\users\sterg\miniconda3\envs\olymp\lib\site-packages (from olymp[all]) (1.5.1)
Requirement already satisfied: numpy in c:\users\sterg\miniconda3\envs\olymp\lib\site-packages (from olymp[all]) (1.23.4)
Collecting SQSnobFit
  Downloading SQSnobFit-0.4.5.tar.gz (29 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sqlalchemy
  Using cached SQLAlchemy-1.4.44-cp39-cp39-win_amd64.whl (1.6 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15; extra == "all" (from olymp[all]) (from versions: 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2)
ERROR: No matching distribution found for tensorflow==1.15; extra == "all"
(olymp) PS C:\Users\sterg\Documents\GitHub\sparks-baird\self-driving-lab-demo>
```

**Comment by anishrao** [comment]
Did you manage to solve this issue?
